[package]
name = "nu_plugin_net"
license = "MIT"
authors = ["Carson <c@rson.riker.me>"]
keywords = ["nushell", "network", "plugin"]
homepage = "https://github.com/fennewald/nu_plugin_net"
repository = "https://github.com/fennewald/nu_plugin_net"
description = "A nushell plugin for enumerating network interfaces in a platform-agnostic way"
version = "1.10.0"
edition = "2021"
readme = "README.md"


[dependencies]
futures = { version = "0.3.31", default-features = false, features = ["alloc", "async-await", "std"] }
log = "0.4.27"
nix = { version = "0.30.1", features = ["fs", "poll", "signal"] }
nu-plugin = "0.104.0"
nu-protocol = { version = "0.104.0", features = ["plugin"] }
pretty_env_logger = "0.5.0"
