[package]
name = "nu_plugin_net"
license = "MIT"
authors = ["Carson <c@rson.riker.me>"]
keywords = ["nushell", "network", "plugin"]
homepage = "https://github.com/fennewald/nu_plugin_net"
repository = "https://github.com/fennewald/nu_plugin_net"
description = "A nushell plugin for enumerating network interfaces in a platform-agnostic way"
version = "2.0.0"
edition = "2021"
readme = "README.md"

[[bin]]
name = "nu_plugin_net"

[lib]

[dependencies]
crossbeam-channel = "0.5.15"
libc = "0.2.171"
nu-plugin = "0.103"
nu-protocol = { version = "0.103", features = ["plugin"] }
tokio = { version = "1.44.1", features = ["full"] }
zerocopy = { version = "0.8.24", features = ["std", "simd-nightly", "derive"] }
